
services:
  app: 
    image: ghcr.io/himti-binus-university/Tecno-2025:${IMAGE_TAG}
    
    container_name: himti_techno_${IMAGE_TAG} 
    restart: always
    
    ports:
      - "${FRONTEND_PORT}:80" 

